persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
log_timestamp_format %d-%m-%y %H:%M:%S

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true
